#version 430

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in; // local workgroup size
layout(binding = 0, rgba8) uniform mediump image2D inputImage;
layout(binding = 1, rgba8) uniform mediump image2D outputImage;

void main()
{
	uint u = gl_GlobalInvocationID.x % imageSize(inputImage).x;
    uint v = gl_GlobalInvocationID.x / imageSize(inputImage).x;
	vec3 color = imageLoad(inputImage, ivec2(u, v)).rgb;
    imageStore(outputImage, ivec2(u, v), vec4(vec3(1.0 - color), 1.0));
}
